import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import { getPublicReport } from "../api/file.api";
import { Bar, Pie } from "react-chartjs-2";
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  BarElement,
  ArcElement,
  Tooltip,
  Legend,
} from "chart.js";


ChartJS.register(
  CategoryScale,
  LinearScale,
  BarElement,
  ArcElement,
  Tooltip,
  Legend
);

const PublicReport = () => {
  const { id } = useParams();
  const [analysis, setAnalysis] = useState(null);
  const [fileName, setFileName] = useState("");

  useEffect(() => {
    const fetchReport = async () => {
      try {
        const res = await getPublicReport(id);
        setAnalysis(res.data.analysis);
        setFileName(res.data.fileName);
      } catch (err) {
        console.error("Failed to load report", err);
      }
    };

    fetchReport();
  }, [id]);

  if (!analysis) {
    return <h2 className="loader">Loading Public Report...</h2>;
  }

  const errorChart = {
    labels: analysis.topErrors.map((e) => e.type),
    datasets: [
      {
        label: "Error Count",
        data: analysis.topErrors.map((e) => e.count),
      },
    ],
  };

  const timeChart = {
    labels: analysis.timeRanges.map((t) => t.range),
    datasets: [
      {
        label: "Errors by Time",
        data: analysis.timeRanges.map((t) => t.count),
      },
    ],
  };

  return (
    <div className="public-report">

      <h1>Log Analysis Report</h1>
      <p className="file-name">{fileName}</p>

      <div className="stats-grid">

        <div className="stat-card">
          <h4>Total Errors</h4>
          <p>{analysis.errorFrequency}</p>
        </div>

        <div className="stat-card">
          <h4>Most Frequent Time Range</h4>
          <p>{analysis.mostFrequentTimeRange}</p>
        </div>

        <div className="stat-card">
          <h4>Unique Error Types</h4>
          <p>{analysis.topErrors.length}</p>
        </div>

      </div>

      <div className="chart-card">
        <h3>Top Errors</h3>
        <Bar data={errorChart} />
      </div>

      <div className="chart-card">
        <h3>Error Distribution by Time</h3>
        <Pie data={timeChart} />
      </div>

      <div className="errors-card">

        <h3>Detected Errors</h3>

        <div className="error-list">
          {analysis.errors.map((err, i) => (
            <div key={i} className="error-item">
              {err}
            </div>
          ))}
        </div>

      </div>

      <div className="footer-note">
        Generated by Log File Intelligence System
      </div>

    </div>
  );
};

export default PublicReport;